### ISSUE TITLE
Ajax view 'advanced_statistics/admin_data' was not found

### ISSUE THREAD

**Issue by guiyom19** [ColdTrick/advanced_statistics#11] opened 2024-09-06 08:16 UTC
**Elgg version**
5 and 6

**Plugin version**
9.1.1 and 10

**Plugin source**
- https://elgg.org/plugins/1148004

**Describe the bug**
As a admin when I go to the /admin/advanced_statistics/users page, an error is showing and nothing is displayed.
The error is **_Ajax view 'advanced_statistics/admin_data' was not found_**
/ajax/view/advanced_statistics/admin_data?section=users&chart=most_used_domains&include_banned_users=1&view=json is getting a 404 error.

**To Reproduce**
Go the one of the /admin/advanced_statistics/ pages

**Screenshots**
![image](https://github.com/user-attachments/assets/e2cd7cb3-7755-4a6b-a321-aac3a55d19b4)

**Comment by jdalsem** [comment] 2024-09-09 06:49
Can you try to flush the caches (on /admin there is a button top right)

**Comment by guiyom19** [comment] 2024-09-13 13:33
Thank you Jeroem, unfortunatly I have the same error after flushing my caches.
I'll try to see if it's not because of my cache configuration.

**Comment by jdalsem** [comment] 2024-11-15 12:46
Closing this for now as it is unable to reproduce

**Closed by jdalsem** 2024-11-15 12:46 UTC
Labels: Bug
